upstream exchange-api-server {
        least_conn;
        server api:3000;
        keepalive 64;
}
server {
    listen 80;

    location / {
        proxy_pass http://exchange-api-server;
        proxy_set_header Host $host;
        proxy_set_header Connection "";
        proxy_http_version 1.1;
    }
}