upstream exchange-api-server {
        server exchange-api-1:3000;
        server exchange-api-2:3000;
        server exchange-api-3:3000;
}
server {
    listen 80;

    location / {
        proxy_pass http://exchange-api-server;
        proxy_set_header Host $host;
        proxy_set_header Connection "";
        proxy_http_version 1.1;
    }
}